### ISSUE TITLE
Siege system 

### ISSUE THREAD

**Issue by ghostfur** [ghostfur/Aion-Lightning-4.9#5]
Siege system is bugged need some new 4.9 upcoding

**Comment by idhacker542** [comment]
what is bugged ?

**Comment by ghostfur** [comment]
I Will check the list and Let you know!

**Comment by kennylucia** [comment]
`com.aionemu.gameserver.services.siegeservice.SiegeException: [SiegeService] Siege Boss not found for siege 10411
        at com.aionemu.gameserver.services.siegeservice.Siege.initSiegeBoss(Siege.java:220) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.siegeservice.FortressSiege.onSiegeStart(FortressSiege.java:103) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.siegeservice.Siege.startSiege(Siege.java:81) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.SiegeService.startSiege(SiegeService.java:283) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.SiegeService.checkSiegeStart(SiegeService.java:266) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.siegeservice.SiegeStartRunnable.run(SiegeStartRunnable.java:34) ~[AL-Game.jar:na]
        at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:48) ~[al-commons.jar:na]
        at com.aionemu.commons.utils.concurrent.RunnableWrapper.run(RunnableWrapper.java:40) [al-commons.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_51]
        at java.lang.Thread.run(Unknown Source) [na:1.7.0_51]
21:00:00.017 WARN [InstantPool-6]: - Exception in a Runnable execution:
com.aionemu.gameserver.services.siegeservice.SiegeException: [SiegeService] Siege Boss not found for siege 10311
        at com.aionemu.gameserver.services.siegeservice.Siege.initSiegeBoss(Siege.java:220) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.siegeservice.FortressSiege.onSiegeStart(FortressSiege.java:103) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.siegeservice.Siege.startSiege(Siege.java:81) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.SiegeService.startSiege(SiegeService.java:283) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.SiegeService.checkSiegeStart(SiegeService.java:266) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.siegeservice.SiegeStartRunnable.run(SiegeStartRunnable.java:34) ~[AL-Game.jar:na]
        at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:48) ~[al-commons.jar:na]
        at com.aionemu.commons.utils.concurrent.RunnableWrapper.run(RunnableWrapper.java:40) [al-commons.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_51]
        at java.lang.Thread.run(Unknown Source) [na:1.7.0_51]
21:00:00.022 INFO [InstantPool-2]: - [FortressSiege] Siege started. [FORTRESS:10211] [RACE: BALAUR] [LegionId:0] [OccupyCount: 0]
21:00:00.027 WARN [InstantPool-3]: - Exception in a Runnable execution:
com.aionemu.gameserver.services.siegeservice.SiegeException: [SiegeService] Siege Boss not found for siege 10111
        at com.aionemu.gameserver.services.siegeservice.Siege.initSiegeBoss(Siege.java:220) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.siegeservice.FortressSiege.onSiegeStart(FortressSiege.java:103) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.siegeservice.Siege.startSiege(Siege.java:81) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.SiegeService.startSiege(SiegeService.java:283) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.SiegeService.checkSiegeStart(SiegeService.java:266) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.siegeservice.SiegeStartRunnable.run(SiegeStartRunnable.java:34) ~[AL-Game.jar:na]
        at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:48) ~[al-commons.jar:na]
        at com.aionemu.commons.utils.concurrent.RunnableWrapper.run(RunnableWrapper.java:40) [al-commons.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_51]
        at java.lang.Thread.run(Unknown Source) [na:1.7.0_51]
21:00:00.029 WARN [InstantPool-2]: - Exception in a Runnable execution:
com.aionemu.gameserver.services.siegeservice.SiegeException: [SiegeService] Siege Boss not found for siege 10211
        at com.aionemu.gameserver.services.siegeservice.Siege.initSiegeBoss(Siege.java:220) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.siegeservice.FortressSiege.onSiegeStart(FortressSiege.java:103) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.siegeservice.Siege.startSiege(Siege.java:81) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.SiegeService.startSiege(SiegeService.java:283) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.SiegeService.checkSiegeStart(SiegeService.java:266) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.siegeservice.SiegeStartRunnable.run(SiegeStartRunnable.java:34) ~[AL-Game.jar:na]
        at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:48) ~[al-commons.jar:na]
        at com.aionemu.commons.utils.concurrent.RunnableWrapper.run(RunnableWrapper.java:40) [al-commons.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_51]
        at java.lang.Thread.run(Unknown Source) [na:1.7.0_51]`
